# WARNING - Generated by {fusen} from dev/flat_nettoyage.Rmd: do not edit by hand

#' Clean up column names in a dataframe
#' 
#' Converts dataframe column names to snake case.
#' 
#' @param data A dataframe
#'
#' @return A dataframe with cleaned up column names, in snake case.
#' 
#' @importFrom magrittr %>%
#' @importFrom stringr str_squish str_to_lower str_replace_all
#' 
#' @examples
#' 
#' clean_titles(data = iris)
#' @export
clean_titles <- function(data){
    names(data) <- names(data) %>% 
      # enlever espaces début, fin ou répétés
      str_squish() %>% 
      # minuscules
      str_to_lower() %>% 
      # remplacer les ponctuations par des underscores
      str_replace_all(pattern = "[:punct:]|[:space:]", replacement = "_")
    return(data)
}
